name: Fetch RSS Feeds

on:
  schedule:
    - cron: '*/4 * * * *'  # Runs every 4 minutes
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Fetch RSS feeds
      run: node fetchRSS.js

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Update RSS feeds'
        git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:main
